### ISSUE TITLE
Depends on incompatible vs-tools version range

### ISSUE THREAD

**Issue by JustinTArthur** [Irrational-Encoding-Wizardry/vs-preview#102]
The latest release of vs-preview pulls in versions of vs-tools that aren't compatible. Specifically the baked-in split planes plugin depends on vs-tools' `stack_clips` to be present when vs-preview is started and this is not the case for all of `vstools>=2.1.0` as found in requirements.txt

In projects that depends on PyPI-distributed IEW and VapourSynth packages, this allows a version of vs-preview to be installed that has no ability to run, due to compatible versions of vs-tools depending on the VapourSynth Python wrapper v63, which is not released on PyPI.
```
$ ./venv/bin/vspreview Scripts/filter_video.vpy
Traceback (most recent call last):
  File "Project/./venv/bin/vspreview", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "Project/venv/lib/python3.11/site-packages/vspreview/init.py", line 124, in main
    main.main_window = MainWindow(Path(os.getcwd()) if args.preserve_cwd else script_path.parent, no_exit)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Project/venv/lib/python3.11/site-packages/vspreview/core/bases.py", line 29, in __call__
    cls.instance = super().__call__(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Project/venv/lib/python3.11/site-packages/vspreview/main/window.py", line 197, in __init__
    Plugins(self)
  File "Project/venv/lib/python3.11/site-packages/vspreview/core/bases.py", line 29, in __call__
    cls.instance = super().__call__(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Project/venv/lib/python3.11/site-packages/vspreview/plugins/__init__.py", line 121, in __init__
    for plugin in self.file_to_plugins(plugin_file):
  File "Project/venv/lib/python3.11/site-packages/vspreview/plugins/__init__.py", line 45, in file_to_plugins
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "Project/venv/lib/python3.11/site-packages/vspreview/plugins/split_view.ppy", line 3, in <module>
    from vstools import check_variable, split, stack_clips, vs
ImportError: cannot import name 'stack_clips' from 'vstools' (Project/venv/lib/python3.11/site-packages/vstools/__init__.py)
Exception ignored in atexit callback: <function _dispose at 0x10b2f58a0>
Traceback (most recent call last):
  File "Project/venv/lib/python3.11/site-packages/vspreview/core/vsenv.py", line 181, in _dispose
    dispose_environment(environment)
  File "Project/venv/lib/python3.11/site-packages/vspreview/core/vsenv.py", line 150, in dispose_environment
    _finalize_core(env._environment.env_id, id(env.core), True)
TypeError: _finalize_core() takes 2 positional arguments but 3 were given
Exception ignored in: <function ManagedEnvironment.__del__ at 0x10b2f45e0>
Traceback (most recent call last):
  File "Project/venv/lib/python3.11/site-packages/vsengine/policy.py", line 348, in __del__
ImportError: sys.meta_path is None, Python is likely shutting down
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: 'vapoursynth.EnvironmentData.__dealloc__'
ImportError: sys.meta_path is None, Python is likely shutting down
```

**Comment by Setsugennoao** [comment]
vapoursynth is not supposed to be installed from pypi
anyways, bumped version for ensuring up-to-date vstools gets installed
though it's always recommended to use vsiew

https://github.com/Irrational-Encoding-Wizardry/vs-preview/commit/e674d2f0ab3a11e6302b604686bdb11eef4acd86

**Comment by YomikoR** [comment]
> vapoursynth is not supposed to be installed from pypi
In IEW toolchain, why

**Comment by Setsugennoao** [comment]
what does that mean in english?
