### ISSUE TITLE
Latest version fails to start

### ISSUE THREAD

**Issue by shssoichiro** [Irrational-Encoding-Wizardry/vs-preview#54]
Steps:

I updated to the latest version using `pip install -U git+https://github.com/Irrational-Encoding-Wizardry/vs-preview.git --user`

Issue:

Upon trying to load vspreview with any vpy script, or even running `vspreview --help` or `vspreview --version`, I receive a crash with the following backtrace:

```
Traceback (most recent call last):
  File "C:\Users\jholm\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\jholm\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\jholm\AppData\Local\Programs\Python\Python310\Scripts\vspreview.exe\__main__.py", line 4, in <module>
  File "C:\Users\jholm\AppData\Roaming\Python\Python310\site-packages\vspreview\__init__.py", line 1, in <module>
    from .init import main  # noqa: F401
  File "C:\Users\jholm\AppData\Roaming\Python\Python310\site-packages\vspreview\init.py", line 18, in <module>
    from .main import MainSettings, MainWindow
  File "C:\Users\jholm\AppData\Roaming\Python\Python310\site-packages\vspreview\main\__init__.py", line 3, in <module>
    from .window import *  # noqa: F401, F403
  File "C:\Users\jholm\AppData\Roaming\Python\Python310\site-packages\vspreview\main\window.py", line 26, in <module>
    from ..toolbars import Toolbars
  File "C:\Users\jholm\AppData\Roaming\Python\Python310\site-packages\vspreview\toolbars\__init__.py", line 12, in <module>
    from .main import MainToolbar
  File "C:\Users\jholm\AppData\Roaming\Python\Python310\site-packages\vspreview\toolbars\main\__init__.py", line 1, in <module>
    from .toolbar import *  # noqa: F401, F403
  File "C:\Users\jholm\AppData\Roaming\Python\Python310\site-packages\vspreview\toolbars\main\toolbar.py", line 13, in <module>
    from .dialog import FramePropsDialog
  File "C:\Users\jholm\AppData\Roaming\Python\Python310\site-packages\vspreview\toolbars\main\dialog.py", line 57, in <module>
    } | dict([
  File "C:\Users\jholm\AppData\Roaming\Python\Python310\site-packages\vspreview\toolbars\main\dialog.py", line 58, in <listcomp>
    _create_enum_props_lut(enum, name)
  File "C:\Users\jholm\AppData\Roaming\Python\Python310\site-packages\vspreview\toolbars\main\dialog.py", line 25, in _create_enum_props_lut
    pretty_name: {
  File "C:\Users\jholm\AppData\Roaming\Python\Python310\site-packages\vspreview\toolbars\main\dialog.py", line 26, in <dictcomp>
    idx: enum.from_param(idx).pretty_string if enum.is_valid(idx) else 'Invalid'
  File "C:\Users\jholm\AppData\Local\Programs\Python\Python310\lib\enum.py", line 437, in __getattr__
    raise AttributeError(name) from None
AttributeError: is_valid
```

I am on Windows 11 with Vapoursynth r61 and Python 3.10.

**Comment by Setsugennoao** [comment]
Bumped version, can you check now?

**Comment by LightArrowsEXE** [comment]
Installing the latest version fixes this issue for me.
