### ISSUE TITLE
Scene Tool Crashing

### ISSUE THREAD

**Issue by Jumaron** [Irrational-Encoding-Wizardry/vs-preview#62]
Hello when i tried to use it it crashes with two crashes.

```PY
CRASH: Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\vspreview\toolbars\scening\dialog.py", line 150, in on_label_changed
    index = self.tableview.selectionModel().selectedRows()[0]
IndexError: list index out of range
```

NEW CRASH:

```PY
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\vspreview\main\timeline.py", line 272, in mouseMoveEvent
    QToolTip.showText(event.globalPosition(), notch.label)
TypeError: showText(QPoint, str, widget: QWidget = None, rect: QRect = {}, msecShowTime: int = -1): argument 1 has unexpected type 'QPointF' 

```

**Comment by JustinTArthur** [comment]
The first stacktrace looks to be from trying to set scene properties from the scene list without having a scene selected. Ultimately we should disable those controls until a scene is selected, but I've added code to ignore those controls as a quick fix in the PR alongside the mouse-hover crash.
