### ISSUE TITLE
Color Management setting QT API update

### ISSUE THREAD

**Issue by LightArrowsEXE** [Irrational-Encoding-Wizardry/vs-preview#71]
```py
2023-02-17 23:48:58.709: root: ERROR: There was an error while loading the script!
| Traceback (most recent call last):
|   File "C:\Users\light\AppData\Local\Programs\Python\Python311\Lib\site-packages\vspreview\main\window.py", line 277, in load_script
|     self.load_storage()
|   File "C:\Users\light\AppData\Local\Programs\Python\Python311\Lib\site-packages\vspreview\utils\utils.py", line 67, in _wrapped
|     ret = func(*args, **kwargs)
|           ^^^^^^^^^^^^^^^^^^^^^
|   File "C:\Users\light\AppData\Local\Programs\Python\Python311\Lib\site-packages\vspreview\main\window.py", line 374, in load_storage
|     self.current_screen = self.app.desktop().screenNumber(self)
|                           ^^^^^^^^^^^^^^^^
| AttributeError: 'QApplication' object has no attribute 'desktop'

Traceback (most recent call last):
  File "C:\Users\light\AppData\Local\Programs\Python\Python311\Lib\site-packages\vspreview\main\window.py", line 710, in moveEvent
    screen_number = self.app.desktop().screenNumber(self)
                    ^^^^^^^^^^^^^^^^
AttributeError: 'QApplication' object has no attribute 'desktop'```

**Comment by LightArrowsEXE** [comment]
Isolated it to `Color Management` being set to `true`.

**Comment by YomikoR** [comment]
I think 21af425 has Qt side fixed, but device context creation fails on my devices with vague error info
`pywintypes.error: (0, 'CreateDC', 'No error message is available')`

**Comment by Setsugennoao** [comment]
> I think [21af425](https://github.com/Irrational-Encoding-Wizardry/vs-preview/commit/21af42589deb00c1806722a4267c906688ab84c0) has Qt side fixed,

Exactly.

>  but device context creation fails on my devices with vague error info `pywintypes.error: (0, 'CreateDC', 'No error message is available')`

Unfortunately, I can't test it :/

**Comment by Setsugennoao** [comment]
Apparently I had an idea on how to fix it.
